name: Test Reusable Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "secrets2=ap-southeast-2" >> $GITHUB_ENV
    
  job1:
    needs: [env]
    uses: ./.github/workflows/reusable-workflows.yml
    with:
      username: chan
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      # secrets1: ${{ secrets.GITHUB_TOKEN }}
