name: Test Reusable Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  secrets2: ap-southeast-2

jobs:
  job1:
    uses: ./.github/workflows/reusable-workflows.yml
    with:
      username: chan
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      # secrets1: ${{ secrets.GITHUB_TOKEN }}
